/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.sergiotepaz.view;

/**
 *
 * @author eduve
 */
public class Juego extends javax.swing.JInternalFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card1 = new javax.swing.JPanel();
        btnSeleccionar1 = new javax.swing.JButton();
        imgSkull1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        card2 = new javax.swing.JPanel();
        btnSeleccionar2 = new javax.swing.JButton();
        imgNerd2 = new javax.swing.JLabel();
        card3 = new javax.swing.JPanel();
        btnSeleccionar3 = new javax.swing.JButton();
        imgPls3 = new javax.swing.JLabel();
        card4 = new javax.swing.JPanel();
        btnSeleccionar4 = new javax.swing.JButton();
        imgHuh4 = new javax.swing.JLabel();
        card5 = new javax.swing.JPanel();
        btnSeleccionar5 = new javax.swing.JButton();
        imgHuh5 = new javax.swing.JLabel();
        card6 = new javax.swing.JPanel();
        btnSeleccionar6 = new javax.swing.JButton();
        imgPls6 = new javax.swing.JLabel();
        card7 = new javax.swing.JPanel();
        btnSeleccionar7 = new javax.swing.JButton();
        imgSkull7 = new javax.swing.JLabel();
        card8 = new javax.swing.JPanel();
        btnSeleccionar8 = new javax.swing.JButton();
        imgNerd8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTurnoActual = new javax.swing.JLabel();

        card1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSeleccionar1.setText("Seleccionar");
        btnSeleccionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionar1ActionPerformed(evt);
            }
        });

        imgSkull1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sergiotepaz/utils/skull.png"))); // NOI18N

        javax.swing.GroupLayout card1Layout = new javax.swing.GroupLayout(card1);
        card1.setLayout(card1Layout);
        card1Layout.setHorizontalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1Layout.createSequentialGroup()
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(imgSkull1))
                    .addGroup(card1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnSeleccionar1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        card1Layout.setVerticalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(imgSkull1)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar1)
                .addGap(26, 26, 26))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Turno del jugador:");

        card2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSeleccionar2.setText("Seleccionar");
        btnSeleccionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionar2ActionPerformed(evt);
            }
        });

        imgNerd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sergiotepaz/utils/nerd.png"))); // NOI18N

        javax.swing.GroupLayout card2Layout = new javax.swing.GroupLayout(card2);
        card2.setLayout(card2Layout);
        card2Layout.setHorizontalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card2Layout.createSequentialGroup()
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(imgNerd2))
                    .addGroup(card2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnSeleccionar2)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        card2Layout.setVerticalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(imgNerd2)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar2)
                .addGap(26, 26, 26))
        );

        card3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSeleccionar3.setText("Seleccionar");
        btnSeleccionar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionar3ActionPerformed(evt);
            }
        });

        imgPls3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sergiotepaz/utils/pls.png"))); // NOI18N

        javax.swing.GroupLayout card3Layout = new javax.swing.GroupLayout(card3);
        card3.setLayout(card3Layout);
        card3Layout.setHorizontalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card3Layout.createSequentialGroup()
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(imgPls3))
                    .addGroup(card3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnSeleccionar3)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        card3Layout.setVerticalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(imgPls3)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar3)
                .addGap(26, 26, 26))
        );

        card4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSeleccionar4.setText("Seleccionar");
        btnSeleccionar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionar4ActionPerformed(evt);
            }
        });

        imgHuh4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sergiotepaz/utils/huh.png"))); // NOI18N

        javax.swing.GroupLayout card4Layout = new javax.swing.GroupLayout(card4);
        card4.setLayout(card4Layout);
        card4Layout.setHorizontalGroup(
            card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card4Layout.createSequentialGroup()
                .addGroup(card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(imgHuh4))
                    .addGroup(card4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnSeleccionar4)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        card4Layout.setVerticalGroup(
            card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card4Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(imgHuh4)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar4)
                .addGap(26, 26, 26))
        );

        card5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSeleccionar5.setText("Seleccionar");
        btnSeleccionar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionar5ActionPerformed(evt);
            }
        });

        imgHuh5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sergiotepaz/utils/huh.png"))); // NOI18N

        javax.swing.GroupLayout card5Layout = new javax.swing.GroupLayout(card5);
        card5.setLayout(card5Layout);
        card5Layout.setHorizontalGroup(
            card5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card5Layout.createSequentialGroup()
                .addGroup(card5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(imgHuh5))
                    .addGroup(card5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnSeleccionar5)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        card5Layout.setVerticalGroup(
            card5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(imgHuh5)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar5)
                .addGap(26, 26, 26))
        );

        card6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSeleccionar6.setText("Seleccionar");
        btnSeleccionar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionar6ActionPerformed(evt);
            }
        });

        imgPls6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sergiotepaz/utils/pls.png"))); // NOI18N

        javax.swing.GroupLayout card6Layout = new javax.swing.GroupLayout(card6);
        card6.setLayout(card6Layout);
        card6Layout.setHorizontalGroup(
            card6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card6Layout.createSequentialGroup()
                .addGroup(card6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card6Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(imgPls6))
                    .addGroup(card6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnSeleccionar6)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        card6Layout.setVerticalGroup(
            card6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card6Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(imgPls6)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar6)
                .addGap(26, 26, 26))
        );

        card7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSeleccionar7.setText("Seleccionar");
        btnSeleccionar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionar7ActionPerformed(evt);
            }
        });

        imgSkull7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sergiotepaz/utils/skull.png"))); // NOI18N

        javax.swing.GroupLayout card7Layout = new javax.swing.GroupLayout(card7);
        card7.setLayout(card7Layout);
        card7Layout.setHorizontalGroup(
            card7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card7Layout.createSequentialGroup()
                .addGroup(card7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card7Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(imgSkull7))
                    .addGroup(card7Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnSeleccionar7)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        card7Layout.setVerticalGroup(
            card7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card7Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(imgSkull7)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar7)
                .addGap(26, 26, 26))
        );

        card8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSeleccionar8.setText("Seleccionar");
        btnSeleccionar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionar8ActionPerformed(evt);
            }
        });

        imgNerd8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sergiotepaz/utils/nerd.png"))); // NOI18N

        javax.swing.GroupLayout card8Layout = new javax.swing.GroupLayout(card8);
        card8.setLayout(card8Layout);
        card8Layout.setHorizontalGroup(
            card8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card8Layout.createSequentialGroup()
                .addGroup(card8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card8Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(imgNerd8))
                    .addGroup(card8Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnSeleccionar8)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        card8Layout.setVerticalGroup(
            card8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card8Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(imgNerd8)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar8)
                .addGap(26, 26, 26))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Seleccione una pareja de cartas");

        lblTurnoActual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(card5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(card2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(card6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(card3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(card4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(card7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(card8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTurnoActual)
                                .addGap(135, 135, 135))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(193, 193, 193)))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTurnoActual))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionar1ActionPerformed

    private void btnSeleccionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionar2ActionPerformed

    private void btnSeleccionar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionar3ActionPerformed

    private void btnSeleccionar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionar4ActionPerformed

    private void btnSeleccionar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionar5ActionPerformed

    private void btnSeleccionar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionar6ActionPerformed

    private void btnSeleccionar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionar7ActionPerformed

    private void btnSeleccionar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionar8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar1;
    private javax.swing.JButton btnSeleccionar2;
    private javax.swing.JButton btnSeleccionar3;
    private javax.swing.JButton btnSeleccionar4;
    private javax.swing.JButton btnSeleccionar5;
    private javax.swing.JButton btnSeleccionar6;
    private javax.swing.JButton btnSeleccionar7;
    private javax.swing.JButton btnSeleccionar8;
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card2;
    private javax.swing.JPanel card3;
    private javax.swing.JPanel card4;
    private javax.swing.JPanel card5;
    private javax.swing.JPanel card6;
    private javax.swing.JPanel card7;
    private javax.swing.JPanel card8;
    private javax.swing.JLabel imgHuh4;
    private javax.swing.JLabel imgHuh5;
    private javax.swing.JLabel imgNerd2;
    private javax.swing.JLabel imgNerd8;
    private javax.swing.JLabel imgPls3;
    private javax.swing.JLabel imgPls6;
    private javax.swing.JLabel imgSkull1;
    private javax.swing.JLabel imgSkull7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTurnoActual;
    // End of variables declaration//GEN-END:variables
}
